services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    image: src:dev
    ports:
      - "5275:5275"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Logs:/app/Logs

