services:
  src:
    build:
      context: .
      dockerfile: .dockerfile
    image: src:dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Logs:/app/Logs

